// DO NOT EDIT MANUALLY!
// Generated by org/jetbrains/kotlin/generators/arguments/GenerateGradleOptions.kt
// To regenerate run 'generateGradleOptions' task
@file:Suppress("RemoveRedundantQualifierName", "Deprecation", "DuplicatedCode")

package org.jetbrains.kotlin.gradle.dsl

interface KotlinJsDceOptions : org.jetbrains.kotlin.gradle.dsl.KotlinCommonToolOptions {

    /**
     * Development mode: don't strip out any code, just copy dependencies
     * Default value: false
     */
    @get:org.gradle.api.tasks.Input
    val devMode: org.gradle.api.provider.Property<kotlin.Boolean>

    /**
     * Output directory
     * Default value: null
     */
    @get:org.gradle.api.tasks.Internal
    val outputDirectory: org.gradle.api.provider.Property<kotlin.String>

    interface KotlinJsDceOptionsDsl : KotlinOptionsDsl<KotlinJsDceOptions> {

        /**
         * Development mode: don't strip out any code, just copy dependencies
         * Default value: false
         */
        @get:org.gradle.api.tasks.Internal
        var devMode: kotlin.Boolean
            get() = options.devMode.get()
            set(value) = options.devMode.set(value)

        /**
         * Output directory
         * Default value: null
         */
        @get:org.gradle.api.tasks.Internal
        var outputDirectory: kotlin.String?
            get() = options.outputDirectory.orNull
            set(value) = options.outputDirectory.set(value)
    }
}
