// DO NOT EDIT MANUALLY!
// Generated by org/jetbrains/kotlin/generators/arguments/GenerateGradleOptions.kt
// To regenerate run 'generateGradleOptions' task
@file:Suppress("RemoveRedundantQualifierName", "Deprecation", "DuplicatedCode")

package org.jetbrains.kotlin.gradle.dsl

interface KotlinJsDceOptions : org.jetbrains.kotlin.gradle.dsl.KotlinCommonToolOptions {

    /**
     * Development mode: don't strip out any code, just copy dependencies
     * Default value: false
     */
    @get:org.gradle.api.tasks.Input
    val devModeProp: org.gradle.api.provider.Property<kotlin.Boolean>

    /**
     * Development mode: don't strip out any code, just copy dependencies
     * Default value: false
     */
    @get:org.gradle.api.tasks.Internal
    var devMode: kotlin.Boolean
        get() = devModeProp.get()
        set(value) = devModeProp.set(value)

    /**
     * Output directory
     * Default value: null
     */
    @get:org.gradle.api.tasks.Internal
    val outputDirectoryProp: org.gradle.api.provider.Property<kotlin.String>

    /**
     * Output directory
     * Default value: null
     */
    @get:org.gradle.api.tasks.Internal
    var outputDirectory: kotlin.String?
        get() = outputDirectoryProp.orNull
        set(value) = outputDirectoryProp.set(value)
}
