// DO NOT EDIT MANUALLY!
// Generated by org/jetbrains/kotlin/generators/arguments/GenerateGradleOptions.kt
// To regenerate run 'generateGradleOptions' task
@file:Suppress("RemoveRedundantQualifierName", "Deprecation", "DuplicatedCode")

package org.jetbrains.kotlin.gradle.dsl

interface KotlinJvmOptions : org.jetbrains.kotlin.gradle.dsl.KotlinCommonOptions {

    /**
     * Generate metadata for Java 1.8 reflection on method parameters
     * Default value: false
     */
    @get:org.gradle.api.tasks.Input
    val javaParameters: org.gradle.api.provider.Property<kotlin.Boolean>

    /**
     * Target version of the generated JVM bytecode (1.6 (DEPRECATED), 1.8, 9, 10, ..., 18), default is 1.8
     * Possible values: "1.6", "1.8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18"
     * Default value: null
     */
    @get:org.gradle.api.tasks.Optional
    @get:org.gradle.api.tasks.Input
    val jvmTarget: org.gradle.api.provider.Property<kotlin.String>

    /**
     * Name of the generated .kotlin_module file
     * Default value: null
     */
    @get:org.gradle.api.tasks.Optional
    @get:org.gradle.api.tasks.Input
    val moduleName: org.gradle.api.provider.Property<kotlin.String>

    /**
     * Don't automatically include the Java runtime into the classpath
     * Default value: false
     */
    @get:org.gradle.api.tasks.Input
    val noJdk: org.gradle.api.provider.Property<kotlin.Boolean>

    /**
     * Use the old JVM backend
     * Default value: false
     */
    @get:org.gradle.api.tasks.Input
    val useOldBackend: org.gradle.api.provider.Property<kotlin.Boolean>

    interface KotlinJvmOptionsDsl : KotlinOptionsDsl<KotlinJvmOptions> {

        /**
         * Generate metadata for Java 1.8 reflection on method parameters
         * Default value: false
         */
        @get:org.gradle.api.tasks.Internal
        var javaParameters: kotlin.Boolean
            get() = options.javaParameters.get()
            set(value) = options.javaParameters.set(value)

        /**
         * Target version of the generated JVM bytecode (1.6 (DEPRECATED), 1.8, 9, 10, ..., 18), default is 1.8
         * Possible values: "1.6", "1.8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18"
         * Default value: null
         */
        @get:org.gradle.api.tasks.Internal
        var jvmTarget: kotlin.String?
            get() = options.jvmTarget.orNull
            set(value) = options.jvmTarget.set(value)

        /**
         * Name of the generated .kotlin_module file
         * Default value: null
         */
        @get:org.gradle.api.tasks.Internal
        var moduleName: kotlin.String?
            get() = options.moduleName.orNull
            set(value) = options.moduleName.set(value)

        /**
         * Don't automatically include the Java runtime into the classpath
         * Default value: false
         */
        @get:org.gradle.api.tasks.Internal
        var noJdk: kotlin.Boolean
            get() = options.noJdk.get()
            set(value) = options.noJdk.set(value)

        /**
         * Use the old JVM backend
         * Default value: false
         */
        @get:org.gradle.api.tasks.Internal
        var useOldBackend: kotlin.Boolean
            get() = options.useOldBackend.get()
            set(value) = options.useOldBackend.set(value)
    }
}
