// DO NOT EDIT MANUALLY!
// Generated by org/jetbrains/kotlin/generators/arguments/GenerateGradleOptions.kt
// To regenerate run 'generateGradleOptions' task
@file:Suppress("RemoveRedundantQualifierName", "Deprecation", "DuplicatedCode")

package org.jetbrains.kotlin.gradle.dsl

interface KotlinCommonToolOptions{

    /**
     * Report an error if there are any warnings
     * Default value: false
     */
    @get:org.gradle.api.tasks.Input
    val allWarningsAsErrorsProp: org.gradle.api.provider.Property<kotlin.Boolean>

    /**
     * Report an error if there are any warnings
     * Default value: false
     */
    @get:org.gradle.api.tasks.Internal
    var allWarningsAsErrors: kotlin.Boolean
        get() = allWarningsAsErrorsProp.get()
        set(value) = allWarningsAsErrorsProp.set(value)

    /**
     * Generate no warnings
     * Default value: false
     */
    @get:org.gradle.api.tasks.Input
    val suppressWarningsProp: org.gradle.api.provider.Property<kotlin.Boolean>

    /**
     * Generate no warnings
     * Default value: false
     */
    @get:org.gradle.api.tasks.Internal
    var suppressWarnings: kotlin.Boolean
        get() = suppressWarningsProp.get()
        set(value) = suppressWarningsProp.set(value)

    /**
     * Enable verbose logging output
     * Default value: false
     */
    @get:org.gradle.api.tasks.Internal
    val verboseProp: org.gradle.api.provider.Property<kotlin.Boolean>

    /**
     * Enable verbose logging output
     * Default value: false
     */
    @get:org.gradle.api.tasks.Internal
    var verbose: kotlin.Boolean
        get() = verboseProp.get()
        set(value) = verboseProp.set(value)

    /**
     * A list of additional compiler arguments
     * Default value: emptyList()
     */
    @get:org.gradle.api.tasks.Input
    val freeCompilerArgsProp: org.gradle.api.provider.ListProperty<kotlin.String>

    /**
     * A list of additional compiler arguments
     * Default value: emptyList()
     */
    @get:org.gradle.api.tasks.Internal
    var freeCompilerArgs: kotlin.collections.List<kotlin.String>
        get() = freeCompilerArgsProp.get()
        set(value) = freeCompilerArgsProp.set(value)
}
