// DO NOT EDIT MANUALLY!
// Generated by org/jetbrains/kotlin/generators/arguments/GenerateGradleOptions.kt
// To regenerate run 'generateGradleOptions' task
@file:Suppress("RemoveRedundantQualifierName", "Deprecation", "DuplicatedCode")

package org.jetbrains.kotlin.gradle.dsl

interface KotlinMultiplatformCommonOptions : org.jetbrains.kotlin.gradle.dsl.KotlinCommonOptions {

    /**
     * Name of the generated .kotlin_module file
     * Default value: null
     */
    @get:org.gradle.api.tasks.Optional
    @get:org.gradle.api.tasks.Input
    val moduleNameProp: org.gradle.api.provider.Property<kotlin.String>

    /**
     * Name of the generated .kotlin_module file
     * Default value: null
     */
    @get:org.gradle.api.tasks.Internal
    var moduleName: kotlin.String?
        get() = moduleNameProp.orNull
        set(value) = moduleNameProp.set(value)
}
