/** This file is generated by {@link :js:js.test:generateJsExportOnFileTestFilesForTS} task. DO NOT MODIFY MANUALLY */

// CHECK_TYPESCRIPT_DECLARATIONS
// RUN_PLAIN_BOX_FUNCTION
// SKIP_MINIFICATION
// SKIP_NODE_JS
// KJS_WITH_FULL_RUNTIME
// INFER_MAIN_MODULE
// MODULE: JS_TESTS
// FILE: qualified.kt

@file:JsExport
@file:JsQualifier("WebAssembly")
package qualified

external interface CompileError

// FILE: notQualified.kt

@file:JsExport
package notQualified

external interface Console

// FILE: member-properties.kt

@file:JsExport

package foo

import notQualified.Console
import qualified.CompileError

interface NonExportedInterface
interface NonExportedGenericInterface<T>
open class NonExportedType(val value: Int)
open class NonExportedGenericType<T>(val value: T)


interface ExportedInterface


fun producer(value: Int): NonExportedType {
    return NonExportedType(value)
}


fun consumer(value: NonExportedType): Int {
    return value.value
}


open class A(var value: NonExportedType) {
    fun <T: NonExportedType> increment(t: T): NonExportedType {
        return NonExportedType(value = t.value + 1)
    }
}


class B(v: Int) : NonExportedType(v)


class C : NonExportedInterface


class D : NonExportedInterface, ExportedInterface


class E : NonExportedType(42), ExportedInterface


class F : A(NonExportedType(42)), NonExportedInterface


class G : NonExportedGenericInterface<NonExportedType>


class H : NonExportedGenericType<NonExportedType>(NonExportedType(42))


fun baz(a: Int): kotlin.js.Promise<Int> {
    return kotlin.js.Promise<Int> { res, rej -> res(a) }
}


fun bar(): Throwable {
    return Throwable("Test Error")
}


val console: Console
    get() = js("console")


val error: CompileError
    get() = js("{}")

typealias NotExportedTypeAlias = NonExportedGenericInterface<NonExportedType>


fun functionWithTypeAliasInside(x: NotExportedTypeAlias): NotExportedTypeAlias {
    return x
}