// DO NOT EDIT MANUALLY!
// Generated by org/jetbrains/kotlin/generators/arguments/GenerateGradleOptions.kt
package org.jetbrains.kotlin.gradle.dsl

@Suppress("DEPRECATION")
enum class ApiVersion (val version: String) {
    KOTLIN_1_0("1.0"),
    KOTLIN_1_1("1.1"),
    KOTLIN_1_2("1.2"),
    KOTLIN_1_3("1.3"),
    KOTLIN_1_4("1.4"),
    KOTLIN_1_5("1.5"),
    KOTLIN_1_6("1.6"),
    KOTLIN_1_7("1.7"),
    KOTLIN_1_8("1.8"),
    KOTLIN_1_9("1.9");

    companion object {
        fun fromVersion(version: String): ApiVersion =
            ApiVersion.values().first { it.version == version }
    }
}
