/*
 * Copyright 2010-2021 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.light.classes.symbol;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link GenerateNewCompilerTests.kt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("analysis/symbol-light-classes/testData/source")
@TestDataPath("$PROJECT_ROOT")
public class FirLightClassForSourceTestGenerated extends AbstractFirLightClassForSourceTest {
    @Test
    public void testAllFilesPresentInSource() throws Exception {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("analysis/symbol-light-classes/testData/source"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("annotation.kt")
    public void testAnnotation() throws Exception {
        runTest("analysis/symbol-light-classes/testData/source/annotation.kt");
    }

    @Test
    @TestMetadata("enumEntry.kt")
    public void testEnumEntry() throws Exception {
        runTest("analysis/symbol-light-classes/testData/source/enumEntry.kt");
    }

    @Test
    @TestMetadata("memberFunction.kt")
    public void testMemberFunction() throws Exception {
        runTest("analysis/symbol-light-classes/testData/source/memberFunction.kt");
    }

    @Test
    @TestMetadata("topLevelFunction.kt")
    public void testTopLevelFunction() throws Exception {
        runTest("analysis/symbol-light-classes/testData/source/topLevelFunction.kt");
    }

    @Test
    @TestMetadata("topLevelProperty.kt")
    public void testTopLevelProperty() throws Exception {
        runTest("analysis/symbol-light-classes/testData/source/topLevelProperty.kt");
    }
}
