// DO NOT EDIT MANUALLY!
// Generated by org/jetbrains/kotlin/generators/arguments/GenerateGradleOptions.kt
// To regenerate run 'generateGradleOptions' task
@file:Suppress("RemoveRedundantQualifierName", "Deprecation", "DuplicatedCode")

package org.jetbrains.kotlin.gradle.dsl

internal class KotlinJsDceOptionsBase @javax.inject.Inject constructor(
    objectFactory: org.gradle.api.model.ObjectFactory
) : org.jetbrains.kotlin.gradle.dsl.KotlinJsDceOptions {

    override val allWarningsAsErrors: org.gradle.api.provider.Property<kotlin.Boolean> =
        objectFactory.property(kotlin.Boolean::class.java).convention(false)

    override val suppressWarnings: org.gradle.api.provider.Property<kotlin.Boolean> =
        objectFactory.property(kotlin.Boolean::class.java).convention(false)

    override val verbose: org.gradle.api.provider.Property<kotlin.Boolean> =
        objectFactory.property(kotlin.Boolean::class.java).convention(false)

    override val freeCompilerArgs: org.gradle.api.provider.ListProperty<kotlin.String> =
        objectFactory.listProperty(kotlin.String::class.java).convention(emptyList())

    override val devMode: org.gradle.api.provider.Property<kotlin.Boolean> =
        objectFactory.property(kotlin.Boolean::class.java).convention(false)

    override val outputDirectory: org.gradle.api.provider.Property<kotlin.String> =
        objectFactory.property(kotlin.String::class.java)

    internal fun toCompilerArguments(args: org.jetbrains.kotlin.cli.common.arguments.K2JSDceArguments) {
        args.allWarningsAsErrors = allWarningsAsErrors.get()
        args.suppressWarnings = suppressWarnings.get()
        args.verbose = verbose.get()
        args.freeArgs += freeCompilerArgs.get()
        args.devMode = devMode.get()
        args.outputDirectory = outputDirectory.orNull
    }

    internal fun fillDefaultValues(args: org.jetbrains.kotlin.cli.common.arguments.K2JSDceArguments) {
        args.allWarningsAsErrors = false
        args.suppressWarnings = false
        args.verbose = false
        args.devMode = false
        args.outputDirectory = null
    }
}
