// DO NOT EDIT MANUALLY!
// Generated by org/jetbrains/kotlin/generators/arguments/GenerateGradleOptions.kt
// To regenerate run 'generateGradleOptions' task
@file:Suppress("RemoveRedundantQualifierName", "Deprecation", "DuplicatedCode")

package org.jetbrains.kotlin.gradle.dsl

internal class KotlinJsOptionsBase @javax.inject.Inject constructor(
    objectFactory: org.gradle.api.model.ObjectFactory
) : org.jetbrains.kotlin.gradle.dsl.KotlinJsOptions {

    override val allWarningsAsErrorsProp: org.gradle.api.provider.Property<kotlin.Boolean> =
        objectFactory.property(kotlin.Boolean::class.java).convention(false)

    override val suppressWarningsProp: org.gradle.api.provider.Property<kotlin.Boolean> =
        objectFactory.property(kotlin.Boolean::class.java).convention(false)

    override val verboseProp: org.gradle.api.provider.Property<kotlin.Boolean> =
        objectFactory.property(kotlin.Boolean::class.java).convention(false)

    override val freeCompilerArgsProp: org.gradle.api.provider.ListProperty<kotlin.String> =
        objectFactory.listProperty(kotlin.String::class.java).convention(emptyList())

    override val apiVersionProp: org.gradle.api.provider.Property<kotlin.String> =
        objectFactory.property(kotlin.String::class.java)

    override val languageVersionProp: org.gradle.api.provider.Property<kotlin.String> =
        objectFactory.property(kotlin.String::class.java)

    override val useFirProp: org.gradle.api.provider.Property<kotlin.Boolean> =
        objectFactory.property(kotlin.Boolean::class.java).convention(false)

    override val friendModulesDisabledProp: org.gradle.api.provider.Property<kotlin.Boolean> =
        objectFactory.property(kotlin.Boolean::class.java).convention(false)

    override val mainProp: org.gradle.api.provider.Property<kotlin.String> =
        objectFactory.property(kotlin.String::class.java).convention("call")

    override val metaInfoProp: org.gradle.api.provider.Property<kotlin.Boolean> =
        objectFactory.property(kotlin.Boolean::class.java).convention(true)

    override val moduleKindProp: org.gradle.api.provider.Property<kotlin.String> =
        objectFactory.property(kotlin.String::class.java).convention("plain")

    override val noStdlibProp: org.gradle.api.provider.Property<kotlin.Boolean> =
        objectFactory.property(kotlin.Boolean::class.java).convention(true)

    override val outputFileProp: org.gradle.api.provider.Property<kotlin.String> =
        objectFactory.property(kotlin.String::class.java)

    override val sourceMapProp: org.gradle.api.provider.Property<kotlin.Boolean> =
        objectFactory.property(kotlin.Boolean::class.java).convention(false)

    override val sourceMapEmbedSourcesProp: org.gradle.api.provider.Property<kotlin.String> =
        objectFactory.property(kotlin.String::class.java)

    override val sourceMapPrefixProp: org.gradle.api.provider.Property<kotlin.String> =
        objectFactory.property(kotlin.String::class.java)

    override val targetProp: org.gradle.api.provider.Property<kotlin.String> =
        objectFactory.property(kotlin.String::class.java).convention("v5")

    override val typedArraysProp: org.gradle.api.provider.Property<kotlin.Boolean> =
        objectFactory.property(kotlin.Boolean::class.java).convention(true)

    internal fun toCompilerArguments(args: org.jetbrains.kotlin.cli.common.arguments.K2JSCompilerArguments) {
        args.allWarningsAsErrors = allWarningsAsErrors
        args.suppressWarnings = suppressWarnings
        args.verbose = verbose
        args.freeArgs += freeCompilerArgs
        args.apiVersion = apiVersion
        args.languageVersion = languageVersion
        args.useFir = useFir
        args.friendModulesDisabled = friendModulesDisabled
        args.main = main
        args.metaInfo = metaInfo
        args.moduleKind = moduleKind
        args.noStdlib = noStdlib
        args.outputFile = outputFile
        args.sourceMap = sourceMap
        args.sourceMapEmbedSources = sourceMapEmbedSources
        args.sourceMapPrefix = sourceMapPrefix
        args.target = target
        args.typedArrays = typedArrays
    }

    internal fun fillDefaultValues(args: org.jetbrains.kotlin.cli.common.arguments.K2JSCompilerArguments) {
        args.allWarningsAsErrors = false
        args.suppressWarnings = false
        args.verbose = false
        args.apiVersion = null
        args.languageVersion = null
        args.useFir = false
        args.friendModulesDisabled = false
        args.main = "call"
        args.metaInfo = true
        args.moduleKind = "plain"
        args.noStdlib = true
        args.outputFile = null
        args.sourceMap = false
        args.sourceMapEmbedSources = null
        args.sourceMapPrefix = null
        args.target = "v5"
        args.typedArrays = true
    }
}
