// DO NOT EDIT MANUALLY!
// Generated by org/jetbrains/kotlin/generators/arguments/GenerateGradleOptions.kt
// To regenerate run 'generateGradleOptions' task
@file:Suppress("RemoveRedundantQualifierName", "Deprecation", "DuplicatedCode")

package org.jetbrains.kotlin.gradle.dsl

internal class KotlinJsDceOptionsBase @javax.inject.Inject constructor(
    objectFactory: org.gradle.api.model.ObjectFactory
) : org.jetbrains.kotlin.gradle.dsl.KotlinJsDceOptions {

    override val allWarningsAsErrorsProp: org.gradle.api.provider.Property<kotlin.Boolean> =
        objectFactory.property(kotlin.Boolean::class.java).convention(false)

    override val suppressWarningsProp: org.gradle.api.provider.Property<kotlin.Boolean> =
        objectFactory.property(kotlin.Boolean::class.java).convention(false)

    override val verboseProp: org.gradle.api.provider.Property<kotlin.Boolean> =
        objectFactory.property(kotlin.Boolean::class.java).convention(false)

    override val freeCompilerArgsProp: org.gradle.api.provider.ListProperty<kotlin.String> =
        objectFactory.listProperty(kotlin.String::class.java).convention(emptyList())

    override val devModeProp: org.gradle.api.provider.Property<kotlin.Boolean> =
        objectFactory.property(kotlin.Boolean::class.java).convention(false)

    override val outputDirectoryProp: org.gradle.api.provider.Property<kotlin.String> =
        objectFactory.property(kotlin.String::class.java)

    internal fun toCompilerArguments(args: org.jetbrains.kotlin.cli.common.arguments.K2JSDceArguments) {
        args.allWarningsAsErrors = allWarningsAsErrors
        args.suppressWarnings = suppressWarnings
        args.verbose = verbose
        args.freeArgs += freeCompilerArgs
        args.devMode = devMode
        args.outputDirectory = outputDirectory
    }

    internal fun fillDefaultValues(args: org.jetbrains.kotlin.cli.common.arguments.K2JSDceArguments) {
        args.allWarningsAsErrors = false
        args.suppressWarnings = false
        args.verbose = false
        args.devMode = false
        args.outputDirectory = null
    }
}
