/*
 * Copyright 2010-2021 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.analysis.api.fir.scopes;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link GenerateNewCompilerTests.kt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("analysis/analysis-api/testData/scopes/memberScopeByCaret")
@TestDataPath("$PROJECT_ROOT")
public class FirMemberScopeByCaretTestGenerated extends AbstractFirMemberScopeByCaretTest {
    @Test
    public void testAllFilesPresentInMemberScopeByCaret() throws Exception {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("analysis/analysis-api/testData/scopes/memberScopeByCaret"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("GenericFromFunctionInLocalClass1.kt")
    public void testGenericFromFunctionInLocalClass1() throws Exception {
        runTest("analysis/analysis-api/testData/scopes/memberScopeByCaret/GenericFromFunctionInLocalClass1.kt");
    }

    @Test
    @TestMetadata("GenericFromFunctionInLocalClass2.kt")
    public void testGenericFromFunctionInLocalClass2() throws Exception {
        runTest("analysis/analysis-api/testData/scopes/memberScopeByCaret/GenericFromFunctionInLocalClass2.kt");
    }
}
